### ISSUE TITLE
2020.12.7官方下载的windows版本 替换后闪退~ 大佬有空看下~

### ISSUE THREAD

**Issue by lhtuling** [hlmd/Postman-cn#10]
2020.12.7官方下载的windows版本 替换后闪退~ 大佬有空看下~

**Comment by hlmd** [comment]
你试试用
C:\Users\用户\AppData\Local\Postman\app-7.36.0\Postman.exe
打开应用程序
![image](https://user-images.githubusercontent.com/45023268/101300922-2d28ae00-3872-11eb-84b8-a912cfdbc1f9.png)

**Comment by lhtuling** [comment]
没有\Postman.exe
![image](https://user-images.githubusercontent.com/44140500/101318684-ae486b00-389b-11eb-93be-0b8d1d8ebef5.png)
打开这个  PostmanCanary.exe   还是闪退

**Comment by hlmd** [comment]
> 没有\Postman.exe
> ![image](https://user-images.githubusercontent.com/44140500/101318684-ae486b00-389b-11eb-93be-0b8d1d8ebef5.png)
> 打开这个 PostmanCanary.exe 还是闪退

![image](https://user-images.githubusercontent.com/45023268/101318934-113a0200-389c-11eb-97d1-736f673544f4.png)
目前只对正式版进行了汉化，体验版没有进行汉化

**Comment by lhtuling** [comment]
好的  我找找正式版下载的  还不知道这个情况~~感谢

**Comment by lhtuling** [comment]
在官网好像没有找到正式版和体验版的区别下载的地方~~

**Comment by lhtuling** [comment]
http://www.pc6.com/softview/SoftView_423615.html
在第三方网站上找到下载了  可以了!  感谢大佬!

**Comment by hlmd** [comment]
> http://www.pc6.com/softview/SoftView_423615.html
> 在第三方网站上找到下载了 可以了! 感谢大佬!

![image](https://user-images.githubusercontent.com/45023268/101423329-c2d84200-3933-11eb-85af-1bd817cb9f66.png)
https://www.postman.com/downloads/
