### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by micropu** [hlmd/Postman-cn#12]
按教程操作无法使用，app.zip 解压&&复制到 应用程序目录/resources/，/resources/里只有一 个文件，app.zip里没有同名文件，怎么替换？

**Comment by hlmd** [comment]
Windows的直接解压就行

**Comment by hlmd** [comment]
解压到当前文件夹，会生成一个app文件夹就可以了    /resources/app/

**Comment by hlmd** [comment]
就是把 解压得到的app文件夹复制到resources目录下面

**Comment by hlmd** [comment]
![image](https://user-images.githubusercontent.com/45023268/102730335-59aef080-436f-11eb-888c-a1859e71830a.png)

**Comment by micropu** [comment]
谢谢，可以了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "黄连木笛"<notifications@github.com&gt;; 
发送时间: 2020年12月21日(星期一) 上午9:32
收件人: "hlmd/Postman-cn"<Postman-cn@noreply.github.com&gt;; 
抄送: "zhipu"<2001972@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hlmd/Postman-cn] 无法使用 (#12)
