### ISSUE TITLE
当前官网postman版本到V8.0.6

### ISSUE THREAD

**Issue by agentptx** [hlmd/Postman-cn#17]
当前官网postman版本到V8.0.6了，如何兼容postmancn-8.0.4?
Thanks!

**Comment by hlmd** [comment]
之前整理电脑的时候，不小心格式化磁盘了，啥也没了😢。
暂时先用8.0.4吧
https://github.com/hlmd/Postman-cn/releases/download/8.0.4/app-8.0.4.rar

**Comment by hlmd** [comment]
新版本正在努力汉化中

**Comment by agentptx** [comment]
OK! 辛苦了。。。
有mac版本的包么，在官网没有找到8.0.4

**Comment by hlmd** [comment]
https://github.com/hlmd/Postman-cn#历史版本下载

**Comment by agentptx** [comment]
Good !!
