### ISSUE TITLE
archlinux 系列现在可以通过包管理器安装了

### ISSUE THREAD

**Issue by kekeimiku** [hlmd/Postman-cn#20]
```shell
yay -S postman-bin-zh
```
https://aur.archlinux.org/packages/postman-bin-zh/

**Comment by hsuehly** [comment]
感谢，就是下载有点慢

**Comment by hsuehly** [comment]
> ```shell
> yay -S postman-bin-zh
> ```
> 
> https://aur.archlinux.org/packages/postman-bin-zh/

更新之后app里面缺少图标文件assets
