### ISSUE TITLE
有没有办法关闭Postman自动更新呢

### ISSUE THREAD

**Issue by MyLovePoppet** [hlmd/Postman-cn#23]
我在设置中关闭了自动更新

![image](https://user-images.githubusercontent.com/40077724/117094584-bba84980-ad96-11eb-841a-c66e02b24a73.png)

但是好像每次postman还是会自动更新，自动更新就得重新下汉化包，老哥有没有啥好的办法来关闭它的自动更新呢？

**Comment by hlmd** [comment]
把需要使用的版本包移出来就可以了，使用这个包里面的Postman
例如：我把app-8.3.0移动到了桌面
![image](https://user-images.githubusercontent.com/45023268/117284822-d9120c00-ae99-11eb-8e29-32058e8f1f5c.png)

**Comment by saxfore** [comment]
> 把需要使用的版本包移出来就可以了，使用这个包里面的Postman
> 例如：我把app-8.3.0移动到了桌面
> ![image](https://user-images.githubusercontent.com/45023268/117284822-d9120c00-ae99-11eb-8e29-32058e8f1f5c.png)

mac版本的怎么搞？？

**Comment by hlmd** [comment]
https://github.com/hlmd/Postman-cn#禁止更新

**Comment by transtone** [comment]
把 `Update.exe` 用一个 txt 空文件改名替换掉。

**Comment by Sc-6-23** [comment]
![屏幕截图 2021-09-06 150601](https://user-images.githubusercontent.com/73343288/132174662-e8b786c7-19cc-4d08-a849-45b25663581c.png)
更新了新版本后旧版本的文件夹可以删除吗？(app-8.10.0)
