### ISSUE TITLE
hosts文件增加了配置,postman还是自动更新.

### ISSUE THREAD

**Issue by stupidzhou** [hlmd/Postman-cn#25]

**Comment by stupidzhou** [comment]
确认hosts修改成功,但软件还是自动进行了更新.请问有和我一样情况的小伙伴吗.

**Comment by hlmd** [comment]
你ping dl.pstmn.io

**Comment by stupidzhou** [comment]
Ping 请求找不到主机 dl.pstmn.io。请检查该名称，然后重试。
我尝试将0.0.0.0         dl.pstmn.io 修改为 127.0.0.1         dl.pstmn.io
出现:正在 Ping dl.pstmn.io [127.0.0.1] 具有 32 字节的数据

**Comment by hlmd** [comment]
这个是检查更新的地址 https://dl.pstmn.io/update/status?channel=stable&currentVersion=8.6.1&arch=64&platform=win64

**Comment by hlmd** [comment]
那你现在应该是访问不了了

**Comment by stupidzhou** [comment]
感谢!问题解决了

**Comment by mirrorHe** [comment]
和你一样  是把0,0,0,0 改成127.0.0.1吗?

**Comment by stupidzhou** [comment]
> 
> 
> 和你一样 是把0,0,0,0 改成127.0.0.1吗?

我修改为127.0.0.1之后postman不再自动更新了,你可以尝试一下.
