### ISSUE TITLE
没有mac版本的吗，大神

### ISSUE THREAD

**Issue by cddehsy** [hlmd/Postman-cn#4]

**Comment by hlmd** [comment]
电脑带不动虚拟机呀

**Comment by sotex** [comment]
我在 linux 上使用没有问题。
我的安装过程：

```bash
# 1、安装 postman
pacman -S postman  # 或 apt install postman

# 2、解压 asar
mkdir postman_cn && cd postman_cn  # 创建临时文件夹，并把下载的 app.zip 放在里面
unzip app.zip # 解压
npm i asar # 下载 arar 解压工具（需要先安装 npm 工具

）
node node_modules/asar/bin/asar.js e app.asar app

# 3、覆盖原版文件
sudo cp -PR app/* /usr/share/postman/app/
```

我重新打了个压缩包在这里

链接: https://pan.baidu.com/s/1_G7CXTXYJmDUprrWNXXWAQ 提取码: 59ec 复制这段内容后打开百度网盘手机App，操作更方便哦

Mac OS 我没有研究过，但可能也差不多吧。你可以尝试看能不能也这么替换。

**Comment by fuermao** [comment]
> 我在 linux 上使用没有问题。
> 我的安装过程：
> 
> ```shell
> # 1、安装 postman
> pacman -S postman  # 或 apt install postman
> 
> # 2、解压 asar
> mkdir postman_cn && cd postman_cn  # 创建临时文件夹，并把下载的 app.zip 放在里面
> unzip app.zip # 解压
> npm i asar # 下载 arar 解压工具（需要先安装 npm 工具
> 
> ）
> node node_modules/asar/bin/asar.js e app.asar app
> 
> # 3、覆盖原版文件
> sudo cp -PR app/* /usr/share/postman/app/
> ```
> 
> 我重新打了个压缩包在这里
> 
> 链接: https://pan.baidu.com/s/1_G7CXTXYJmDUprrWNXXWAQ 提取码: 59ec
> 
> Mac OS 我没有研究过，但可能也差不多吧。你可以尝试看能不能也这么替换。

可以这么替换，我已经测试了
