### ISSUE TITLE
macOS 添加禁用解析到/etc/hosts还是会自动更新

### ISSUE THREAD

**Issue by xiaolizi9** [hlmd/Postman-cn#40]
<img width="825" alt="WX20211103-143211@2x" src="https://user-images.githubusercontent.com/46665565/140017906-cce63afc-f04e-4831-b08d-4178e1424399.png">

已经添加解析规则了, 关闭再打开还是会自动更新到最新版本

**Comment by hlmd** [comment]
ping dl.pstmn.io 呢

**Comment by xiaolizi9** [comment]
> ping dl.pstmn.io

![image](https://user-images.githubusercontent.com/46665565/140674971-4a795193-f731-4610-afca-5f11fbbee1bb.png)

**Comment by hlmd** [comment]
那就不会呀

**Comment by hlmd** [comment]
为啥是超时呢，不应该是127.0.0.1吗

**Comment by xiaolizi9** [comment]
> 为啥是超时呢，不应该是127.0.0.1吗

的确是超时的, 配置上面也放了, 0.0.0.0和127.0.0.1都添加了

**Comment by hlmd** [comment]
你使用了代理吗

**Comment by xiaolizi9** [comment]
> 你使用了代理吗

使用科学上网vpn了

**Comment by xiaolizi9** [comment]
> 你使用了代理吗

使用科学上网vpn就没有办法解决了吗

**Comment by hlmd** [comment]
你不绕过局域网就行

**Comment by ivshow** [comment]
使用vpn后，确实就失效了
