### ISSUE TITLE
9.1.3版本文档保存时报错,无法存储

### ISSUE THREAD

**Issue by Sercl** [hlmd/Postman-cn#42]
官方9.1.3英文版本正常,9.1.3汉化后就无法正常保存.

控制台提示Invalid params uid or updates.

9.0.7的汉化版可以正常保存文档,但是无法使用"流"

![image](https://user-images.githubusercontent.com/35843500/141976928-4fbd52ed-36e7-48fe-b530-99ff42796552.png)

![image](https://user-images.githubusercontent.com/35843500/141976751-5722a8bc-c3bc-4e09-bb51-6fcf34ccfec2.png)

没找到具体问题所在,对比了913官方的代码并没有发现不同的地方,希望大大能修复,感谢

**Comment by hlmd** [comment]
文档无法保存问题已解决
