### ISSUE TITLE
汉化后授权报错

### ISSUE THREAD

**Issue by a421127199** [hlmd/Postman-cn#5]
![image](https://user-images.githubusercontent.com/3792992/91531038-b6107f00-e93e-11ea-85aa-d3a3b9a55841.png)
![image](https://user-images.githubusercontent.com/3792992/91531062-c1fc4100-e93e-11ea-8aa3-e97de1a0822f.png)
汉化后，原本使用Bear授权的接口报错，这个地方的Header名字应该继续使用原本的英文，而不应该被替换成中文

**Comment by zgcwkj** [comment]
一样有这个问题~~~

**Comment by hlmd** [comment]
> ![图片](https://user-images.githubusercontent.com/3792992/91531038-b6107f00-e93e-11ea-85aa-d3a3b9a55841.png)
> ![图片](https://user-images.githubusercontent.com/3792992/91531062-c1fc4100-e93e-11ea-8aa3-e97de1a0822f.png)
> 汉化后，原本使用Bear授权的接口报错，这个地方的Header名字应该继续使用原本的英文，而不应该被替换成中文

**Comment by hlmd** [comment]
> ![图片](https://user-images.githubusercontent.com/3792992/91531038-b6107f00-e93e-11ea-85aa-d3a3b9a55841.png)
> ![图片](https://user-images.githubusercontent.com/3792992/91531062-c1fc4100-e93e-11ea-8aa3-e97de1a0822f.png)
> 汉化后，原本使用Bear授权的接口报错，这个地方的Header名字应该继续使用原本的英文，而不应该被替换成中文
